spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos
    username: pos
    password: P@s+9res
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
# Server configuration
server:
  port: 8888 #set your port
#server.port=8888
#server.ssl.key-store=classpath:bootsecurity.p12
#server.ssl.enabled=true
#server.ssl.key-alias=bootsecurity
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=bootsecurity
#spring.datasource.platform=postgres
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://rawoona.com:5433/pos
#spring.datasource.url=jdbc:postgresql://pos_postgres:5432/pos
#spring.datasource.url=jdbc:postgresql://postgres:5432/scott
#spring.datasource.url=jdbc:postgresql://mv3lscmt01tevn1:5432/scott
#spring.datasource.username=scott
#spring.datasource.password=example
#spring.datasource.username=pos
#spring.datasource.password=P@s+9res
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#server.error.include-message=always
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.roles=admin

# Spring Boot configuration
